import { Link } from "wouter";
import { motion } from "framer-motion";
import { MarketingNav } from "@/components/marketing/MarketingNav";
import { MarketingFooter } from "@/components/marketing/MarketingFooter";

const fade = (delay = 0) => ({
  initial: { opacity: 0, y: 18 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.45, delay },
});

export default function Terms() {
  return (
    <div className="public-marketing-surface min-h-screen bg-[#F8FAFC] text-foreground overflow-x-hidden">
      <MarketingNav />

      <section className="relative border-b border-border/60 bg-white overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(70%_55%_at_20%_0%,rgba(37,99,235,0.08),transparent_60%)]" />
        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 pt-16 pb-14">
          <motion.h1 {...fade(0)} className="text-3xl sm:text-4xl font-semibold tracking-tight">
            Terms of Use
          </motion.h1>
          <motion.p {...fade(0.05)} className="mt-3 text-muted-foreground">
            Last updated: March 2026
          </motion.p>
        </div>
      </section>

      <section className="max-w-3xl mx-auto px-4 sm:px-6 py-14 lg:py-20">
        <motion.article
          {...fade(0.08)}
          className="prose prose-slate prose-sm max-w-none bg-white rounded-2xl border border-border p-8 sm:p-12 prose-headings:font-semibold prose-headings:tracking-tight prose-p:text-muted-foreground prose-li:text-muted-foreground shadow-sm"
        >
          <p>
            This application provides AI-powered language assistance tools intended for language practice, study, and professional
            development.
          </p>

          <p>
            The service is not designed to replace professional interpretation services or to be used in violation of employer,
            contractor, or platform policies.
          </p>

          <p>
            Users are solely responsible for ensuring that their use of this tool complies with any contractual obligations,
            confidentiality agreements, employer rules, or applicable laws.
          </p>

          <p>The platform does not assume responsibility for how users apply the outputs generated by the tool.</p>

          <p>
            By using this service, you agree that the developers are not liable for any misuse of the tool in professional
            environments where such tools may be restricted.
          </p>

          <h2>Subscription Plans</h2>
          <p>
            New accounts receive a 7-day free trial with a daily usage limit of 120 minutes (2 hours). Existing users keep the
            trial limits and duration that were originally assigned to their account. After the trial period, continued access
            requires a paid subscription. Plans are billed monthly and may be cancelled at any time:
          </p>
          <ul>
            <li>
              <strong>Basic</strong> – $59/month – up to 5 hours of interpreting per day
            </li>
            <li>
              <strong>Professional</strong> – $99/month – unlimited interpreting hours as offered in the product; a daily platform cap
              may still apply
            </li>
            <li>
              <strong>Platinum</strong> – $179/month – unlimited interpreting hours as offered in the product, including the premium
              translation tier where applicable; a daily platform cap may still apply
            </li>
          </ul>

          <h2>Acceptable Use</h2>
          <p>
            You agree not to misuse the service. You may not use this tool to process content you do not have the legal right to
            handle, to attempt to reverse-engineer proprietary technology, or to violate any applicable laws or regulations.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            The service is provided &quot;as is.&quot; We make no warranties about accuracy, availability, or fitness for a particular
            purpose. Our liability is limited to the amount you paid for the service in the preceding month.
          </p>

          <h2>Termination</h2>
          <p>
            We reserve the right to terminate accounts that violate these terms. You may cancel your account at any time. Upon
            termination, access to the service will cease at the end of the billing period.
          </p>

          <h2>Changes to Terms</h2>
          <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>

          <h2>Responsible Use Policy</h2>

          <p>This tool is intended for language learning, practice, and general assistance.</p>

          <p>
            Users must not use this tool in situations where third-party AI tools are prohibited by their employer, contracting
            organization, or interpreting platform.
          </p>

          <p>Users are responsible for complying with confidentiality rules and professional standards associated with interpretation services.</p>

          <p>The developers do not collect, store, or retain audio conversations or transcripts from user sessions.</p>

          <p>The tool processes audio in real time only to generate temporary outputs for user assistance.</p>

          <h2>Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:legal@interpreterai.com" className="text-primary font-medium no-underline hover:underline">
              legal@interpreterai.com
            </a>
            .
          </p>
        </motion.article>

        <div className="mt-10 flex flex-wrap justify-center gap-8 text-sm text-muted-foreground">
          <Link href="/privacy" className="hover:text-foreground transition-colors">
            Privacy Policy
          </Link>
          <Link href="/security" className="hover:text-foreground transition-colors">
            Security
          </Link>
        </div>
      </section>

      <MarketingFooter />
    </div>
  );
}
