import { useLocation } from "wouter";
import { ArrowLeft, Mic2 } from "lucide-react";

export default function Terms() {
  const [, setLocation] = useLocation();
  return (
    <div className="min-h-screen bg-[#f5f5f7] py-12 px-6">
      <div className="max-w-3xl mx-auto">
        <button onClick={() => setLocation("/")} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <div className="flex items-center gap-3 mb-8">
          <div className="w-9 h-9 bg-primary rounded-xl flex items-center justify-center">
            <Mic2 className="w-4 h-4 text-white" />
          </div>
          <span className="font-display font-bold text-lg">InterpreterAI</span>
        </div>
        <div className="bg-white rounded-2xl border border-border shadow-sm p-8 prose prose-sm max-w-none">
          <h1>Terms of Use</h1>
          <p className="text-muted-foreground text-sm">Last updated: March 2026</p>

          <p>This application provides AI-powered language assistance tools intended for language practice, study, and professional development.</p>

          <p>The service is not designed to replace professional interpretation services or to be used in violation of employer, contractor, or platform policies.</p>

          <p>Users are solely responsible for ensuring that their use of this tool complies with any contractual obligations, confidentiality agreements, employer rules, or applicable laws.</p>

          <p>The platform does not assume responsibility for how users apply the outputs generated by the tool.</p>

          <p>By using this service, you agree that the developers are not liable for any misuse of the tool in professional environments where such tools may be restricted.</p>

          <h2>Subscription Plans</h2>
          <p>New accounts receive a 7-day free trial with a daily usage limit of 60 minutes (1 hour), using the full interpreter stack. Existing users keep the trial limits and duration that were originally assigned to their account. After the trial period, continued access requires a paid subscription. Plans are billed monthly and may be cancelled at any time:</p>
          <ul>
            <li><strong>Basic</strong> – $40/month – up to 5 hours/day</li>
            <li><strong>Professional</strong> – $80/month – up to 9 hours/day (shown in the product as unlimited-style usage; a daily platform cap still applies)</li>
            <li><strong>Unlimited</strong> – $120/month – up to 9 hours/day (same cap behavior as Professional; branding may describe unlimited-style usage)</li>
          </ul>

          <h2>Acceptable Use</h2>
          <p>You agree not to misuse the service. You may not use this tool to process content you do not have the legal right to handle, to attempt to reverse-engineer proprietary technology, or to violate any applicable laws or regulations.</p>

          <h2>Limitation of Liability</h2>
          <p>The service is provided "as is." We make no warranties about accuracy, availability, or fitness for a particular purpose. Our liability is limited to the amount you paid for the service in the preceding month.</p>

          <h2>Termination</h2>
          <p>We reserve the right to terminate accounts that violate these terms. You may cancel your account at any time. Upon termination, access to the service will cease at the end of the billing period.</p>

          <h2>Changes to Terms</h2>
          <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>

          <h2>Responsible Use Policy</h2>

          <p>This tool is intended for language learning, practice, and general assistance.</p>

          <p>Users must not use this tool in situations where third-party AI tools are prohibited by their employer, contracting organization, or interpreting platform.</p>

          <p>Users are responsible for complying with confidentiality rules and professional standards associated with interpretation services.</p>

          <p>The developers do not collect, store, or retain audio conversations or transcripts from user sessions.</p>

          <p>The tool processes audio in real time only to generate temporary outputs for user assistance.</p>

          <h2>Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:legal@interpreterai.com">legal@interpreterai.com</a>.</p>
        </div>

        <div className="flex items-center justify-center gap-6 mt-8 text-sm text-muted-foreground">
          <button onClick={() => setLocation("/terms")} className="hover:text-foreground transition-colors">Terms of Use</button>
          <button onClick={() => setLocation("/privacy")} className="hover:text-foreground transition-colors">Privacy Policy</button>
        </div>
      </div>
    </div>
  );
}
